require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AwardsController do

  # This should return the minimal set of attributes required to create a valid
  # Award. As you add validations to Award, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all awards as @awards" do
      award = Award.create! valid_attributes
      get :index
      assigns(:awards).should eq([award])
    end
  end

  describe "GET show" do
    it "assigns the requested award as @award" do
      award = Award.create! valid_attributes
      get :show, :id => award.id.to_s
      assigns(:award).should eq(award)
    end
  end

  describe "GET new" do
    it "assigns a new award as @award" do
      get :new
      assigns(:award).should be_a_new(Award)
    end
  end

  describe "GET edit" do
    it "assigns the requested award as @award" do
      award = Award.create! valid_attributes
      get :edit, :id => award.id.to_s
      assigns(:award).should eq(award)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Award" do
        expect {
          post :create, :award => valid_attributes
        }.to change(Award, :count).by(1)
      end

      it "assigns a newly created award as @award" do
        post :create, :award => valid_attributes
        assigns(:award).should be_a(Award)
        assigns(:award).should be_persisted
      end

      it "redirects to the created award" do
        post :create, :award => valid_attributes
        response.should redirect_to(Award.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved award as @award" do
        # Trigger the behavior that occurs when invalid params are submitted
        Award.any_instance.stub(:save).and_return(false)
        post :create, :award => {}
        assigns(:award).should be_a_new(Award)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Award.any_instance.stub(:save).and_return(false)
        post :create, :award => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested award" do
        award = Award.create! valid_attributes
        # Assuming there are no other awards in the database, this
        # specifies that the Award created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Award.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => award.id, :award => {'these' => 'params'}
      end

      it "assigns the requested award as @award" do
        award = Award.create! valid_attributes
        put :update, :id => award.id, :award => valid_attributes
        assigns(:award).should eq(award)
      end

      it "redirects to the award" do
        award = Award.create! valid_attributes
        put :update, :id => award.id, :award => valid_attributes
        response.should redirect_to(award)
      end
    end

    describe "with invalid params" do
      it "assigns the award as @award" do
        award = Award.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Award.any_instance.stub(:save).and_return(false)
        put :update, :id => award.id.to_s, :award => {}
        assigns(:award).should eq(award)
      end

      it "re-renders the 'edit' template" do
        award = Award.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Award.any_instance.stub(:save).and_return(false)
        put :update, :id => award.id.to_s, :award => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested award" do
      award = Award.create! valid_attributes
      expect {
        delete :destroy, :id => award.id.to_s
      }.to change(Award, :count).by(-1)
    end

    it "redirects to the awards list" do
      award = Award.create! valid_attributes
      delete :destroy, :id => award.id.to_s
      response.should redirect_to(awards_url)
    end
  end

end
