require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EducationsController do

  # This should return the minimal set of attributes required to create a valid
  # Education. As you add validations to Education, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all educations as @educations" do
      education = Education.create! valid_attributes
      get :index
      assigns(:educations).should eq([education])
    end
  end

  describe "GET show" do
    it "assigns the requested education as @education" do
      education = Education.create! valid_attributes
      get :show, :id => education.id.to_s
      assigns(:education).should eq(education)
    end
  end

  describe "GET new" do
    it "assigns a new education as @education" do
      get :new
      assigns(:education).should be_a_new(Education)
    end
  end

  describe "GET edit" do
    it "assigns the requested education as @education" do
      education = Education.create! valid_attributes
      get :edit, :id => education.id.to_s
      assigns(:education).should eq(education)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Education" do
        expect {
          post :create, :education => valid_attributes
        }.to change(Education, :count).by(1)
      end

      it "assigns a newly created education as @education" do
        post :create, :education => valid_attributes
        assigns(:education).should be_a(Education)
        assigns(:education).should be_persisted
      end

      it "redirects to the created education" do
        post :create, :education => valid_attributes
        response.should redirect_to(Education.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved education as @education" do
        # Trigger the behavior that occurs when invalid params are submitted
        Education.any_instance.stub(:save).and_return(false)
        post :create, :education => {}
        assigns(:education).should be_a_new(Education)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Education.any_instance.stub(:save).and_return(false)
        post :create, :education => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested education" do
        education = Education.create! valid_attributes
        # Assuming there are no other educations in the database, this
        # specifies that the Education created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Education.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => education.id, :education => {'these' => 'params'}
      end

      it "assigns the requested education as @education" do
        education = Education.create! valid_attributes
        put :update, :id => education.id, :education => valid_attributes
        assigns(:education).should eq(education)
      end

      it "redirects to the education" do
        education = Education.create! valid_attributes
        put :update, :id => education.id, :education => valid_attributes
        response.should redirect_to(education)
      end
    end

    describe "with invalid params" do
      it "assigns the education as @education" do
        education = Education.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Education.any_instance.stub(:save).and_return(false)
        put :update, :id => education.id.to_s, :education => {}
        assigns(:education).should eq(education)
      end

      it "re-renders the 'edit' template" do
        education = Education.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Education.any_instance.stub(:save).and_return(false)
        put :update, :id => education.id.to_s, :education => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested education" do
      education = Education.create! valid_attributes
      expect {
        delete :destroy, :id => education.id.to_s
      }.to change(Education, :count).by(-1)
    end

    it "redirects to the educations list" do
      education = Education.create! valid_attributes
      delete :destroy, :id => education.id.to_s
      response.should redirect_to(educations_url)
    end
  end

end
