require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JobHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # JobHistory. As you add validations to JobHistory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all job_histories as @job_histories" do
      job_history = JobHistory.create! valid_attributes
      get :index
      assigns(:job_histories).should eq([job_history])
    end
  end

  describe "GET show" do
    it "assigns the requested job_history as @job_history" do
      job_history = JobHistory.create! valid_attributes
      get :show, :id => job_history.id.to_s
      assigns(:job_history).should eq(job_history)
    end
  end

  describe "GET new" do
    it "assigns a new job_history as @job_history" do
      get :new
      assigns(:job_history).should be_a_new(JobHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested job_history as @job_history" do
      job_history = JobHistory.create! valid_attributes
      get :edit, :id => job_history.id.to_s
      assigns(:job_history).should eq(job_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JobHistory" do
        expect {
          post :create, :job_history => valid_attributes
        }.to change(JobHistory, :count).by(1)
      end

      it "assigns a newly created job_history as @job_history" do
        post :create, :job_history => valid_attributes
        assigns(:job_history).should be_a(JobHistory)
        assigns(:job_history).should be_persisted
      end

      it "redirects to the created job_history" do
        post :create, :job_history => valid_attributes
        response.should redirect_to(JobHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved job_history as @job_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobHistory.any_instance.stub(:save).and_return(false)
        post :create, :job_history => {}
        assigns(:job_history).should be_a_new(JobHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobHistory.any_instance.stub(:save).and_return(false)
        post :create, :job_history => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested job_history" do
        job_history = JobHistory.create! valid_attributes
        # Assuming there are no other job_histories in the database, this
        # specifies that the JobHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JobHistory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => job_history.id, :job_history => {'these' => 'params'}
      end

      it "assigns the requested job_history as @job_history" do
        job_history = JobHistory.create! valid_attributes
        put :update, :id => job_history.id, :job_history => valid_attributes
        assigns(:job_history).should eq(job_history)
      end

      it "redirects to the job_history" do
        job_history = JobHistory.create! valid_attributes
        put :update, :id => job_history.id, :job_history => valid_attributes
        response.should redirect_to(job_history)
      end
    end

    describe "with invalid params" do
      it "assigns the job_history as @job_history" do
        job_history = JobHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobHistory.any_instance.stub(:save).and_return(false)
        put :update, :id => job_history.id.to_s, :job_history => {}
        assigns(:job_history).should eq(job_history)
      end

      it "re-renders the 'edit' template" do
        job_history = JobHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobHistory.any_instance.stub(:save).and_return(false)
        put :update, :id => job_history.id.to_s, :job_history => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested job_history" do
      job_history = JobHistory.create! valid_attributes
      expect {
        delete :destroy, :id => job_history.id.to_s
      }.to change(JobHistory, :count).by(-1)
    end

    it "redirects to the job_histories list" do
      job_history = JobHistory.create! valid_attributes
      delete :destroy, :id => job_history.id.to_s
      response.should redirect_to(job_histories_url)
    end
  end

end
