require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrainingsController do

  # This should return the minimal set of attributes required to create a valid
  # Training. As you add validations to Training, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all trainings as @trainings" do
      training = Training.create! valid_attributes
      get :index
      assigns(:trainings).should eq([training])
    end
  end

  describe "GET show" do
    it "assigns the requested training as @training" do
      training = Training.create! valid_attributes
      get :show, :id => training.id.to_s
      assigns(:training).should eq(training)
    end
  end

  describe "GET new" do
    it "assigns a new training as @training" do
      get :new
      assigns(:training).should be_a_new(Training)
    end
  end

  describe "GET edit" do
    it "assigns the requested training as @training" do
      training = Training.create! valid_attributes
      get :edit, :id => training.id.to_s
      assigns(:training).should eq(training)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Training" do
        expect {
          post :create, :training => valid_attributes
        }.to change(Training, :count).by(1)
      end

      it "assigns a newly created training as @training" do
        post :create, :training => valid_attributes
        assigns(:training).should be_a(Training)
        assigns(:training).should be_persisted
      end

      it "redirects to the created training" do
        post :create, :training => valid_attributes
        response.should redirect_to(Training.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved training as @training" do
        # Trigger the behavior that occurs when invalid params are submitted
        Training.any_instance.stub(:save).and_return(false)
        post :create, :training => {}
        assigns(:training).should be_a_new(Training)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Training.any_instance.stub(:save).and_return(false)
        post :create, :training => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested training" do
        training = Training.create! valid_attributes
        # Assuming there are no other trainings in the database, this
        # specifies that the Training created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Training.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => training.id, :training => {'these' => 'params'}
      end

      it "assigns the requested training as @training" do
        training = Training.create! valid_attributes
        put :update, :id => training.id, :training => valid_attributes
        assigns(:training).should eq(training)
      end

      it "redirects to the training" do
        training = Training.create! valid_attributes
        put :update, :id => training.id, :training => valid_attributes
        response.should redirect_to(training)
      end
    end

    describe "with invalid params" do
      it "assigns the training as @training" do
        training = Training.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Training.any_instance.stub(:save).and_return(false)
        put :update, :id => training.id.to_s, :training => {}
        assigns(:training).should eq(training)
      end

      it "re-renders the 'edit' template" do
        training = Training.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Training.any_instance.stub(:save).and_return(false)
        put :update, :id => training.id.to_s, :training => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested training" do
      training = Training.create! valid_attributes
      expect {
        delete :destroy, :id => training.id.to_s
      }.to change(Training, :count).by(-1)
    end

    it "redirects to the trainings list" do
      training = Training.create! valid_attributes
      delete :destroy, :id => training.id.to_s
      response.should redirect_to(trainings_url)
    end
  end

end
