require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WarsController do

  # This should return the minimal set of attributes required to create a valid
  # War. As you add validations to War, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all wars as @wars" do
      war = War.create! valid_attributes
      get :index
      assigns(:wars).should eq([war])
    end
  end

  describe "GET show" do
    it "assigns the requested war as @war" do
      war = War.create! valid_attributes
      get :show, :id => war.id.to_s
      assigns(:war).should eq(war)
    end
  end

  describe "GET new" do
    it "assigns a new war as @war" do
      get :new
      assigns(:war).should be_a_new(War)
    end
  end

  describe "GET edit" do
    it "assigns the requested war as @war" do
      war = War.create! valid_attributes
      get :edit, :id => war.id.to_s
      assigns(:war).should eq(war)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new War" do
        expect {
          post :create, :war => valid_attributes
        }.to change(War, :count).by(1)
      end

      it "assigns a newly created war as @war" do
        post :create, :war => valid_attributes
        assigns(:war).should be_a(War)
        assigns(:war).should be_persisted
      end

      it "redirects to the created war" do
        post :create, :war => valid_attributes
        response.should redirect_to(War.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved war as @war" do
        # Trigger the behavior that occurs when invalid params are submitted
        War.any_instance.stub(:save).and_return(false)
        post :create, :war => {}
        assigns(:war).should be_a_new(War)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        War.any_instance.stub(:save).and_return(false)
        post :create, :war => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested war" do
        war = War.create! valid_attributes
        # Assuming there are no other wars in the database, this
        # specifies that the War created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        War.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => war.id, :war => {'these' => 'params'}
      end

      it "assigns the requested war as @war" do
        war = War.create! valid_attributes
        put :update, :id => war.id, :war => valid_attributes
        assigns(:war).should eq(war)
      end

      it "redirects to the war" do
        war = War.create! valid_attributes
        put :update, :id => war.id, :war => valid_attributes
        response.should redirect_to(war)
      end
    end

    describe "with invalid params" do
      it "assigns the war as @war" do
        war = War.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        War.any_instance.stub(:save).and_return(false)
        put :update, :id => war.id.to_s, :war => {}
        assigns(:war).should eq(war)
      end

      it "re-renders the 'edit' template" do
        war = War.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        War.any_instance.stub(:save).and_return(false)
        put :update, :id => war.id.to_s, :war => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested war" do
      war = War.create! valid_attributes
      expect {
        delete :destroy, :id => war.id.to_s
      }.to change(War, :count).by(-1)
    end

    it "redirects to the wars list" do
      war = War.create! valid_attributes
      delete :destroy, :id => war.id.to_s
      response.should redirect_to(wars_url)
    end
  end

end
